name: Package snapshot

permissions:
  contents: read

on:
  workflow_dispatch:

jobs:
  package:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: rustup toolchain install
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc,aarch64-pc-windows-msvc
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x
      - name: Build Quiver MSIX bundle
        run: .\build.ps1
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: Quiver_msixbundle
          path: ./_Publish/*.msixbundle
